print("Ne kadar oldu bu hayata geleli?")
print("Söyle, ne olacaksın büyüyünce")
print("Diye sorulan sorular tarih oldu")
print("Ama senin kafan hala dolu")
print("İşte benim, işte senin, işte onun diye")
print("Paylaşıyorsun hayatı üç kuruş sevginle")
print("Ne? o da mı aldattı seni be?")
print("Eee? ne kaldı geriye?")
print("Bak sen ne yazık ki klasik bir tablosun dostum")
print("Ne yaparsan yap boşsun")
print("Tamam okumuşsun, ama yetmez")
print("Sadece bununla dertler bitmez")
print("Çıkacaksın kabuğundan, bunalımdan kurtaracaksın kendini")
print("Ona göre yaşamayı bırakıp döneceksin gerçeklere")
print("Ama önce")
print("Bir kadın çizeceksin")
print("Onun gibi bırakıp gitmeyecek")
print("Saklayıp gömeceksin")
print("Kimseler sevemeyecek")
print("Şimdi bunlar yetmez gibi bir de, kendini aşka mı bıraktın, hadi be")
print("Bırak adam gibi şeylerle uğraşmayı")
print("Herkes gibi takıl, yaşa hayatını")
print("Takılamıyorsan bile rol yap, ne yap et ama yarat kendi yalan dünyanı")
print("Çünkü bunlar para ediyor, baksana sevgi bile yalan olmuş")
print("Piyasada kavrulmuş, herkes kudurmuş")
print("Canım dediğin bile arkandan vurmuş")
print("Tüm bunları bilerek yaşa ve sakın")
print("Ama sakın içindekileri tüketeyim deme")
print("Bir gün gelecek göstereceksin kendini, sevgini, neler istediğini")
print("Şimdilik alacaksın eline kalemi, kusacak dökeceksin nefretini")
print("Bir kadın çizeceksin")
print("Onun gibi bırakıp gitmeyecek")
print("Saklayıp gömeceksin")
print("Kimseler sevemeyecek")
print("Birden duracaksın soracaksın kendine")
print("Neden bu düzen böyle? neden herkes sahte?")
print("Sonra bakacaksın, göreceksin çaren yok")
print("Devam edeceksin? yalandan yaşamaya")
print("Bir kadın çizeceksin")
print("Onun gibi bırakıp gitmeyecek")
print("Saklayıp gömeceksin")
print("Kimseler sevemeyecek")
print("Bir gün gelecek göstereceksin kendini, sevgini, neler istediğini")
print("Şimdilik alacaksın eline kalemi, kusacak dökeceksin nefretini")
print("Çıkacaksın kabuğundan, bunalımdan kurtaracaksın kendini")
print("Ona göre yaşamayı bırakıp döneceksin (gerçeklere)")
print("Bırakıp döneceksin gerçeklere")
print("Bir gün gelecek göstereceksin kendini, sevgini, neler istediğini")
print("Şimdilik alacaksın eline kalemi, kusacak dökeceksin nefretini")
print("Çıkacaksın kabuğundan, bunalımdan kurtaracaksın kendini")
print("Ona göre yaşamayı bırakıp döneceksin gerçeklere")